CREATE TABLE IF NOT EXISTS airports (
	id integer(10),
	ident varchar(10),
	type varchar(30),
	name varchar(255),
	latitude_deg varchar(20),
	longitude_deg varchar(20),
	elevation_ft integer(10),
	continent varchar(10),
	iso_country varchar(10),
	iso_region varchar(10),
	municipality varchar(100),
	scheduled_service varchar(5),
	gps_code varchar(10),
	iata_code varchar(5),
	local_code varchar(10),
	home_link varchar(255),
	wikipedia_link varchar(255),
	keywords varchar(255),
	primary key(id),
	key(iata_code),
	key(ident)
);
